language: python
python: 3.5
sudo: false
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=freeze

matrix:
  include:
    - python: 3.3
      env: TOX_ENV=py33
    - python: 3.6
      env: TOX_ENV=py36
    - os: osx
      # Using "generic" because osx in Travis doesn't support python
      language: generic
      env:
        - TOX_ENV=py27
        - PYTHON_VERSION='2.7'
    - os: osx
      language: generic
      env:
        - TOX_ENV=py35
        - PYTHON_VERSION='3.5.4'
    - os: osx
      language: generic
      env:
        - TOX_ENV=py36
        - PYTHON_VERSION='3.6.3'

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+[\w\-]*$/

before_install: |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # From https://pythonhosted.org/CodeChat/.travis.yml.html
      brew install pyenv-virtualenv
      pyenv install $PYTHON_VERSION
      export PYENV_VERSION=$PYTHON_VERSION
      export PATH="/Users/travis/.pyenv/shims:${PATH}"
      pyenv-virtualenv venv
      source venv/bin/activate
      # A manual check that the correct version of Python is running.
      python --version
      pip install -U pip
    fi

install:
  # FIXME pin virtualenv to provide tests support for python 3.3,
  # should be removed after dropping support of python 3.3 in shub
  - pip install -U tox twine wheel codecov virtualenv==15.2.0

script: tox -e $TOX_ENV

after_success:
  - codecov

before_deploy:
  - if [ $TOX_ENV == freeze ] || [[ $TRAVIS_OS_NAME == osx && $TOX_ENV == py35 ]] ; then tar -czf dist_bin/shub-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x64.tar.gz -C dist_bin shub; fi

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: scrapinghub
    password:
      secure: CJWIRI51KvqZrkPf7At1li+bbAZ/pN3iWRUPy0JaKWAC8O8B+GljXQxiXisPyLL1pIikcfLYZScOsKEhE+Uon/beeL1TPimVU3ELr7GYzuIkl3eK7quFUOiJ7glEggA5UyGNmk6goMVgaBQEOwT3gwH2LYwd1uFRvQsgIPY+tks=
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      repo: scrapinghub/shub
      condition: "$TRAVIS_OS_NAME == linux && $TOX_ENV == py35"
  - provider: releases
    api_key:
      secure: aGbfure96ZxoeZzqckgXVvr1iafipuiSeJ8+i32ldCDV0F+u+QYwKKiYbIdaKJquzlqqknfixICJKW4CjDxx41anK4H1fvAA02uzirOzadPRFPPvNMUgZ6dhHs7Go4ZyrLxb95za5L3ZVoyi7EB18AI5VcCgGw/jLKYwgXga+Qk=
    file: dist_bin/shub-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x64.tar.gz
    skip_cleanup: true
    draft: true
    on:
      tags: true
      repo: scrapinghub/shub
      condition: "$TOX_ENV == freeze || ($TRAVIS_OS_NAME == osx && $TOX_ENV == py35)"
