language: python
python: 2.7
sudo: false
matrix:
  include:
    - os: osx
      # Using "generic" because osx in Travis doesn't support python
      language: generic

branches:
  only:
    - master
    - /^v\d+\.\d+$/

install:
  - "./.travis-workarounds.sh"
  - '[ "$TRAVIS_OS_NAME" != osx ] || source ~/virtualenv/python2.7/bin/activate'
  - pip install -U tox twine wheel

script: tox -e py27,freeze
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: CJWIRI51KvqZrkPf7At1li+bbAZ/pN3iWRUPy0JaKWAC8O8B+GljXQxiXisPyLL1pIikcfLYZScOsKEhE+Uon/beeL1TPimVU3ELr7GYzuIkl3eK7quFUOiJ7glEggA5UyGNmk6goMVgaBQEOwT3gwH2LYwd1uFRvQsgIPY+tks=
  on:
    tags: true
    all_branches: true
    repo: scrapinghub/shub
    condition: "$TRAVIS_OS_NAME == linux"
