language: python
python: 3.6
sudo: false
env:
  - TOX_ENV=py27
  - TOX_ENV=py36
  - TOX_ENV=freeze

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.9
      env: TOX_ENV=py39
    - os: osx
      # Using "generic" because osx in Travis doesn't support python
      language: generic
      env:
        - TOX_ENV=py27
        - PYTHON_VERSION='2.7.18'
    - os: osx
      language: generic
      env:
        - TOX_ENV=py36
        - PYTHON_VERSION='3.6.9'
    - os: osx
      language: generic
      env:
        - TOX_ENV=py37
        - PYTHON_VERSION='3.7.7'
    - os: osx
      language: generic
      env:
        - TOX_ENV=py38
        - PYTHON_VERSION='3.8.0'
    - os: osx
      language: generic
      env:
        - TOX_ENV=py39
        - PYTHON_VERSION='miniconda3-3.9.1'
    - os: osx
      language: generic
      env:
        - TOX_ENV=freeze
        - PYTHON_VERSION='3.6.9'

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+[\w\-]*$/

before_install: |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # From https://pythonhosted.org/CodeChat/.travis.yml.html
      export HOMEBREW_NO_AUTO_UPDATE=1
      brew install pyenv-virtualenv
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
      # See https://github.com/travis-ci/travis-ci/issues/4834, but
      # ignore py27 due to https://github.com/pyenv/pyenv/issues/484
      if [[ "$TOX_ENV" != "py27" ]]; then
        export PYTHON_CONFIGURE_OPTS="--enable-shared"
      fi
      pyenv install $PYTHON_VERSION
      export PYENV_VERSION=$PYTHON_VERSION
      pyenv virtualenv venv
      pyenv activate venv
      # A manual check that the correct version of Python is running.
      python --version
      pip install -U pip
    fi

install:
  - pip install -U tox twine wheel codecov virtualenv

script: tox -e $TOX_ENV

after_success:
  - codecov

before_deploy:
  - if [ $TOX_ENV == freeze ] ; then tar -czf dist_bin/shub-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x64.tar.gz -C dist_bin shub; fi

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: scrapinghub
    password:
      secure: CJWIRI51KvqZrkPf7At1li+bbAZ/pN3iWRUPy0JaKWAC8O8B+GljXQxiXisPyLL1pIikcfLYZScOsKEhE+Uon/beeL1TPimVU3ELr7GYzuIkl3eK7quFUOiJ7glEggA5UyGNmk6goMVgaBQEOwT3gwH2LYwd1uFRvQsgIPY+tks=
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      repo: scrapinghub/shub
      condition: "$TRAVIS_OS_NAME == linux && $TOX_ENV == py38"
  - provider: releases
    api_key:
      secure: KXxQpLnv/Blgxp10iSBHe1ygciXmgKpXDuSLkXolOyS2xx7IEYbR1ArqESrhMWz66MOpYaVxMYKEBKskFOUYNKZq19shkYDMebNwSG6m8Nb1yAaYVtx4G/OzbLjtbEQwQy0wOS0ogw7m0jCywu+92VPwae8zXLXhjCU3c2yofgk=
    file: dist_bin/shub-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x64.tar.gz
    skip_cleanup: true
    draft: true
    on:
      tags: true
      repo: scrapinghub/shub
      condition: "$TOX_ENV == freeze"
